name: Deploy Cloud Functions

env:
  ACCUWEATHER_API_KEY: ${{ secrets.ACCUWEATHER_API_KEY }}
  ADMIN_GROUP_ID: ${{ secrets.ADMIN_GROUP_ID }}
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  CHAT_ID: ${{ secrets.CHAT_ID }}
  FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'functions/**'
jobs:
  build_and_deploy:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/functions/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Build Cloud Functions
        run: cd functions && npm ci
      - name: Create SA key
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > $HOME/gcloud.json
      - name: Deploy Cloud Functions
        run: export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud.json && npx firebase-tools deploy --only functions --json
